### PR TITLE
bump: version to 1.1.0 and support SQLAlchemy 2.0

### PR DESCRIPTION
**Pull request by jetjinser**

### CODE REVIEW

**Comment by chenzl25** [comment]
> NOTE
When creating tables using SQLAlchemy 2.0, BIGINT types will automatically be converted to BIGSERIAL types, which is not supported in RisingWave.

**Comment by jetjinser** [comment]
> > NOTE
> > When creating tables using SQLAlchemy 2.0, BIGINT types will automatically be converted to BIGSERIAL types, which is not supported in RisingWave.
> 
> There is a known issue in our document website https://docs.risingwave.com/docs/current/python-client-libraries/ . Could you please check it for this PR?

No, he has no problem now.
The test code I'm using is:
```python
create_table = DDL("CREATE TABLE t (bi BIGINT)")
with cnx.connect() as conn:
    conn.execute(create_table)

print(pd.read_sql_table("t", cnx))
```

It can be observed in the log of RisingWave that the type of `bi` is still `BIGINT`.

**Review by chenzl25 — APPROVED** [review]
LGTM

**Comment by chenzl25** [comment]
@neverchanje , the documentation of SQL Alchemy seems out of date, do you have any context about the compatibilities issue of SQL Alchemy 1.4?

**Review by neverchanje — APPROVED** [review]

**Review by KeXiangWang — APPROVED** [review]

**Comment by neverchanje** [comment]
I will update it once this new version gets released.

**Review by yuhao-su — APPROVED** [review]

**Pull request merged**
